[package]
name = "mold"
version.workspace = true
edition = "2024"
license.workspace = true

[[bin]]
name = "mold"
path = "src/main.rs"

[dependencies]
mold_syntax.workspace = true
mold_lexer.workspace = true
mold_parser.workspace = true
mold_hir.workspace = true
mold_completion.workspace = true
mold_format.workspace = true
atty = "0.2"
