[package]
name = "mold_lexer"
version.workspace = true
edition = "2024"
license.workspace = true

[dependencies]
mold_syntax.workspace = true
text-size.workspace = true

[dev-dependencies]
insta.workspace = true
