[package]
name = "mold_parser"
version.workspace = true
edition = "2024"
license.workspace = true

[dependencies]
mold_syntax.workspace = true
mold_lexer.workspace = true
cstree.workspace = true
text-size.workspace = true

[dev-dependencies]
insta.workspace = true
proptest.workspace = true
